"use client"

import { Navigation } from '@/components/Navigation';

export default function TermsOfServicePage() {
  return (
    <main className="min-h-screen bg-background">
      <Navigation />
      
      <div className="container mx-auto max-w-4xl px-4 py-20 pb-32">
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-8">Terms of Service</h1>
        
        <div className="text-muted-foreground space-y-8 leading-relaxed prose prose-invert max-w-none">
          <section>
            <p>Last Updated: March 2026</p>
            <p className="mt-4">
              Welcome to ChatPMT! Please read carefully through our Terms of Service. By logging in or engaging with our platform and its generative AI systems, you agree to these legal conditions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">1. Acceptance of Terms</h2>
            <p>
              By signing up for ChatPMT AI, you solidify an agreement with the clauses outlined here. If these terms are not agreeable, we respectfully request that you refrain from using the platform's features and templates.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">2. Account Management</h2>
            <p>
              Security and honesty are vital. You agree to register using accurate personal or organizational data. We require you to maintain the secrecy of your login status. If any unpermitted security breaches occur under your identity, ChatPMT AI cannot be held legally or financially culpable.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">3. Usage of GenAI Features & Credits</h2>
            <ul className="list-disc pl-6 mt-2 space-y-2">
              <li><strong>Fair Usage:</strong> Generating malicious, unethical, or systematically harmful content via our AI integrations is explicitly forbidden and will result in a permanent ban.</li>
              <li><strong>Credit Allocation:</strong> Subscriptions and bought credit packs ("Pay As You Go") represent usage rights on our platform. Credits cannot directly be cashed out for fiat currency.</li>
              <li><strong>Uptime:</strong> While we guarantee near 99% uptime, occasional server and maintenance windows are part of the ecosystem. We don’t hold total responsibility for generative API downtime on the host's end.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">4. Intellectual Property</h2>
            <p>
              All proprietary brand graphics, website UI frameworks, our specific prompt architecture (Template Library), and the foundational application code belong entirely to ChatPMT AI. However, **you** retain full creative ownership over any final text or outputs generated by the AI based on your original inputs.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">5. Refund & Payment Policy</h2>
            <p>
              All transactions conducted, including subscriptions and one-time credits, are finalized through Razorpay. If functional system errors actively disrupt your purchase or if you cancel recurring plans according to the required timeframe, specific exceptions might apply. 
            </p>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-foreground mb-4">6. Changes to Terms</h2>
            <p>
               We retain the right to modify these Terms. Continued navigation and usage of our platform post any update constitutes acceptance of the new protocols.
            </p>
          </section>

        </div>
      </div>
      
      <footer className="container mx-auto px-4 py-8 border-t border-muted text-center text-muted-foreground text-sm">
        © 2026 ChatPMT AI. All Rights Reserved.
      </footer>
    </main>
  );
}
